### 1. 마이페이지 테스트
GET http://localhost:8080/api/member/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzcxNzk2ODgwLCJleHAiOjE3NzE4MDA0ODB9.9iIpTGLMv85b1Vy2JulcIhljYjoCzn75Ih_sE1N9474
